name: workflow to build, test and staging deploy
run-name: Run workflow to build, test and staging deploy
on:
    push:
        branches:
            - "*"
    pull_request:
        types: [opened]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 14

            - name: Install dependencies
              run: npm install --frozen-lockfile

            - name: Build typescript project
              run: npm run build

            - name: Build Docker containers
              run: docker-compose up -d

    test:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 14

            - name: Install dependencies
              run: npm install

            - name: Testing app with Jest
              run: npm run test && echo '✅ ✅ Tests passed!'

    # deploy-staging:
    #    runs-on: ubuntu-latest
    #   needs: [build, test]
    #  if: ${{ github.ref == 'refs/heads/main' }}
    # steps:
    #    - name: deploy
    #     uses: fjogeleit/http-request-action@v1
    #    with:
    #       url: ${{ secrets.ACTIONS_STAGING_DEPLOY_KEY }}
