name: Deploy application to production
run-name: Run Deploy application to production

on:
    workflow_dispatch:

jobs:
    deploy-production:
        runs-on: ubuntu-latest
        if: ${{ github.ref == 'refs/heads/main' }}
        steps:
            - name: deploy
              uses: fjogeleit/http-request-action@v1
              with:
                  url: ${{ secrets.ACTIONS_PRODUCTION_DEPLOY_KEY }}
