FROM node:lts-alpine3.17

WORKDIR /app
COPY package*.json ./
RUN npm install 

COPY . .

# Adicione um arquivo de entrada personalizado (entrypoint.sh)
##COPY entrypointprod.sh /app/entrypointprod.sh
##RUN chmod +x /app/entrypointprod.sh

# Atualize o comando CMD para usar o arquivo de entrada personalizado
CMD ["npm","run","start"]