version: "3.8"
name: "shopbuddy"

services:
    #redis:
    #    image: redis:7.0.9
    #    container_name: redis
    #    command: redis-server --requirepass ${REDIS_PASSWORD} --user ${REDIS_USER}
    #    restart: always
    #    ports:
    #        - "6379:6379"
    #    env_file:
    #        - .env
    svcredis:
        image: bitnami/redis
        expose:
            - 6379
        ports:
            - 6370:6379
        environment:
            - TZ=America/Sao_Paulo
            - ALLOW_EMPTY_PASSWORD=yes

    mongo:
        build: ./server/src/database/
        container_name: mongo${NODE_ENV}
        restart: always
        ports:
            - "28:27017"
        volumes:
            - mongodb-data-dev:/data/db
        env_file:
            - .env

    app:
        build: .
        container_name: appshop-dev
        restart: always
        env_file:
            - .env
        ports:
            - "${PORT}:${PORT}"
        volumes:
            - .:/app/
            - /app/node_modules
        # environment:
        #   - REDIS_DB=redis
        #   - MONGO_DB=mongo
        depends_on:
            - svcredis
            - mongo
        command: npm run dev

volumes:
    mongodb-data-dev:

networks:
    shop_buddy:
        driver: bridge
