version: "3.8"
name: "shopbuddy"

services:
    #redis:
    #    image: redis:7.0.9
    #    container_name: redis
    #    command: redis-server --requirepass ${REDIS_PASSWORD} --user ${REDIS_USER}
    #    restart: always
    #    ports:
    #        - "6379:6379"
    #    env_file:
    #        - .env

    mongo:
        build: ./server/src/database/
        container_name: mongo
        restart: always
        volumes:
            - mongodb-data:/data/db
        env_file:
            - .env
            - server/config/.env

    app:
        build: .
        container_name: app
        restart: always
        env_file:
            - server/config/.env
        ports:
            - "${PORT}:${PORT}"
        volumes:
            - .:/app/
            - /app/node_modules
        # environment:
        #   - REDIS_DB=redis
        #   - MONGO_DB=mongo
        depends_on:
            # - redis
            - mongo

volumes:
    mongodb-data:

networks:
    shop_buddy:
        driver: bridge
