version: "3.8"
name: "shopbuddystaging"

services:
    #redis:
    #    image: redis:7.0.9
    #    container_name: redis
    #    command: redis-server --requirepass ${REDIS_PASSWORD} --user ${REDIS_USER}
    #    restart: always
    #    ports:
    #        - "6379:6379"
    #    env_file:
    #        - .env

    mongo:
        build: ./server/src/database/
        container_name: mongo${NODE_ENV}
        restart: always
        ports:
            - "26:27017"
        volumes:
            - mongodb-data-staging:/data/db
        env_file:
            - .env

    app:
        build: .
        container_name: appshop-staging
        restart: always
        env_file:
            - .env
        ports:
            - "${PORT}:${PORT}"
        volumes:
            - /app
        # environment:
        #   - REDIS_DB=redis
        #   - MONGO_DB=mongo
        depends_on:
            # - redis
            - mongo
        command: sh -c "npm run prestart && npm run start"

volumes:
    mongodb-data-staging:

networks:
    shop_buddy:
        driver: bridge
