version: "3.8"
name: "shopbuddytest"

services:
    svcredis:
        image: bitnami/redis
        expose:
            - 6379
        ports:
            - 6371:6379
        environment:
            - TZ=America/Sao_Paulo
            - ALLOW_EMPTY_PASSWORD=yes

    mongotest:
        build: ./server/src/database/
        container_name: mongotest
        #restart: always
        ports:
            - "30:27017"
        volumes:
            - mongodb-data-test:/data/db
        env_file:
            - .env

    app:
        build: .
        container_name: appshop-test
        env_file:
            - .env
        ports:
            - "4019:4019"
        volumes:
            - /app
        # environment:
        #   - REDIS_DB=redis
        #   - MONGO_DB=mongo
        depends_on:
            - svcredis
            - mongotest
        command: npm run test

volumes:
    mongodb-data-test:

networks:
    shop_buddy:
        driver: bridge
