version: "3.8"
name: "shopbuddy"

services:
    #redis:
    #    image: redis:7.0.9
    #    container_name: redis
    #    command: redis-server --requirepass ${REDIS_PASSWORD} --user ${REDIS_USER}
    #    restart: always
    #    ports:
    #        - "6379:6379"
    #    env_file:
    #        - .env

    mongo:
        build: ./server/src/database/
        container_name: mongo
        restart: always
        ports:
            - "28:27017"
        volumes:
            - mongodb-data:/data/db
        env_file:
            - .env
            - server/config/.env

    appshop:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: appshop
        restart: always
        env_file:
            - server/config/.env
        ports:
            - "${PORT}:${PORT}"
        volumes:
            - .:/app/
        # environment:
        #   - REDIS_DB=redis
        #   - MONGO_DB=mongo
        depends_on:
            # - redis
            - mongo
        command: npm run test

volumes:
    mongodb-data:

networks:
    shop_buddy:
        driver: bridge
