version: "3.8"
name: "shopbuddystaging"

services:
    svcredis:
        image: bitnami/redis
        expose:
            - 6379
        ports:
            - 6372:6379
        environment:
            - TZ=America/Sao_Paulo
            - ALLOW_EMPTY_PASSWORD=yes

    mongo:
        build: ./server/src/database/
        container_name: mongo${NODE_ENV}
        restart: always
        ports:
            - "26:27017"
        volumes:
            - mongodb-data-staging:/data/db
        env_file:
            - .env

    app:
        build: .
        container_name: appshop-staging
        restart: always
        env_file:
            - .env
        ports:
            - "${PORT}:${PORT}"
       # volumes:
        #    - /app
        # environment:
        #   - REDIS_DB=redis
        #   - MONGO_DB=mongo
        depends_on:
            - svcredis
            - mongo
        command: npm run start

volumes:
    mongodb-data-staging:

networks:
    shop_buddy:
        driver: bridge
