version: "3.8"
name: "shopbuddy"

services:
    #redis:
    #    image: redis:7.0.9
    #    container_name: redis
    #    command: redis-server --requirepass ${REDIS_PASSWORD} --user ${REDIS_USER}
    #    restart: always
    #    ports:
    #        - "6379:6379"
    #    env_file:
    #        - .env

    mongo:
        image: mongo:6.0.4
        container_name: mongo
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongodb-data:/data/db
        env_file:
            - .env

    app:
        build: .
        container_name: app
        restart: always
        ports:
            - "4444:4000" #backend
            - "4445:4001" #fronted
        volumes:
            - ./server:/app/server #backend
            - ./client:/app/client #frontend
        # environment:
        #   - REDIS_DB=redis
        #   - MONGO_DB=mongo
        depends_on:
            # - redis
            - mongo

volumes:
    mongodb-data:

networks:
    shop_buddy:
        driver: bridge
