name: Workflow to build, test and staging deploy
run-name: Run Workflow build, test and staging deploy
on:
    push:
        branches-ignore:
            - main
    pull_request:
        types: [opened]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install dependencies
              run: npm install --frozen-lockfile

            - name: Install client dependencies
              working-directory: ./client
              run: yarn install

            - name: Build typescript project
              run: npm run build --if-present

    test:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install dependencies
              run: npm install

            - name: Testing app with Jest
              run: npm run test && echo '✅ ✅ Tests passed!'

    deploy-staging:
        runs-on: [self-hosted, shopbuddy-staging]
        needs: [build, test]
        if: ${{ github.ref == 'refs/heads/staging' }}

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3
            # Runs a single command using the runners shell
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - run: npm install

            - name: Install client dependencies
              working-directory: ./client
              run: yarn install

            - name: Create .env file
              run: |
                  echo "PORT=${{ vars.MY_PORT_STAGING }}" >> .env
                  cat .env
              # Add other variables as needed

            - run: npm run build --if-present
            - run: npm run test
            - run: pm2 restart server
